<h1>Demonstration of Cross Product using weekly sales to get total</h1>

In [4]:
import numpy as np
np.random.seed(0)
#Number of jars sold
sales_amounts = np.random.randint(20, size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [6]:
#Create weekly sales dataframe
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts,
                           index = ['Mon','Tue','Wed','Thurs','Fri'],
                           columns = ['Almond Butter', 'Peanut Butter', 'Cashew Butter']
                           )
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [8]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [10]:
#Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=['Price'],
                            columns = ['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [12]:
#shapes aren't alligned. Transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [13]:
#Create Daily Sales
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thurs  Fri
Price  240  138  458    232  142

In [15]:
#Because daily_sales is in rows, we want it in columns to add it into df
# We can transpose the daily_sales column and then add it
weekly_sales['Total ($)'] = daily_sales.T 

In [16]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142